### ISSUE TITLE
HTML nahled na wysiwyg

### ISSUE THREAD

**Issue by Tomucha** [fnx-io/fnx_ui#16]
Kamo: fnx-wysiwyg-rich, potrebuju dalsi ikonku do toolbaru, prepnuti na HTML verzi a zpet.

V HTML verzi se to zobrazuje v textarea a muzu editovat primo HTML source toho wysiwygu. A muzu se prepnout zpatky na wysiwyg pohled.

Ju? Material ikona "code" (https://material.io/icons/#ic_code)

**Comment by tenhobi** [comment]
Otestuj prosím, mělo by být ok.
