### ISSUE TITLE
Esc pro zabaleni dropdownu zabali i cele dialogove okno

### ISSUE THREAD

**Issue by Tomucha** [fnx-io/fnx_ui#17]
Asi by to chtelo nejaky stop propagation:

Když si rozbalím DATE PICKER a chci ho zase zabalit klávesou Esc, tak se chybně zavře celý dialog, místo aby se zavřel jen ten DATE PICKER. Lze to opravit?

**Comment by tenhobi** [comment]
Toto by mělo fungovat už z https://github.com/fnx-io/fnx_ui/commit/4713dc532e571cfde22ca1c3de16e4db80c7c747. Ještě jednou jsem to otestoval (Chrome i Dartium, myš i klávesnice) a pokud máš v `fnx-modal` otevřený `fnx-select`, `fnx-autocomplete` nebo `fnx-date` (`fnx-date-picker`), nejdříve se zavře dropdown a teprve až pokud nic není v modalu otevřené, zavře se modál.
